name: CI/CD for React App

on:
  push:
    branches:
      - master  # Adjust this according to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build with linting warnings suppressed
      env:
        CI: false  # Set CI=false to suppress linting warnings
      run: npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master  # Adjust if you're deploying to a different branch
        FOLDER: build     # Adjust if your build output folder is different
