name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Build Docker image
      run: |
        docker build -t us.icr.io/sn-labs-anamikaa/medical_app .
        docker tag us.icr.io/sn-labs-anamikaa/medical_app:latest us.icr.io/sn-labs-anamikaa/medical_app:latest
      
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} us.icr.io

    - name: Docker push
      run: docker push us.icr.io/sn-labs-anamikaa/medical_app:latest

    - name: Deploy to IBM Code Engine
      run: |
        ibmcloud ce app update --name my-app --image us.icr.io/sn-labs-anamikaa/medical_app:latest
